# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'popupviewtest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for popupviewtest
  pod 'ExytePopupView'
end
